org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
flutter.compileSdkVersion=36
flutter.targetSdkVersion=36
flutter.minSdkVersion=21
flutter.versionCode=1
flutter.versionName=1.0
flutter.ndkVersion=25.1.8937393
